import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sudeep99
 */
public class progress extends javax.swing.JFrame {

    /**
     * Creates new form progress
     */
    public progress() {
        initComponents();
        //UIManager.put("ProgressBar.selectionBackground",Color.blue);

        Thread t;
        t = new Thread() {
     @Override
     public void run() {
         int i = 0;
         while (i <= 100) {
             pbar.setValue(i);
             if(i<100){
                 Border border = BorderFactory.createTitledBorder("Reading...");//pbar.setBorder(border);
                 pbar.setStringPainted(true);
                 pbar.setBackground(Color.BLUE);
             }
             else{
                 Border border = BorderFactory.createTitledBorder("Loaded...");
                 pbar.setBorder(border);
                 pbar.setBackground(Color.gray);
                 if(i==100){
                     changePage(); 
                     dispose(); //closing current JFrame
                 }
             }
             try {
                 sleep(10);                 
             } 
             catch (InterruptedException ex) {
                 //Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
             }
             i++;
         }
     }
        };
        t.start();
           

    } 
   
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pbar.setBackground(java.awt.Color.blue);
        pbar.setForeground(new java.awt.Color(0, 0, 0));
        pbar.setBorderPainted(false);
        pbar.setFocusCycleRoot(true);
        pbar.setStringPainted(true);
        getContentPane().add(pbar);
        pbar.setBounds(80, 470, 460, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokedex/icons/Loading_Background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 300, 900, 310);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokedex/icons/Unova_Background.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-310, -50, 950, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
  
 public static void changePage()
   {     
       Select_region selectRegion = new Select_region();
       selectRegion.setVisible(true);
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progress().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar pbar;
    // End of variables declaration//GEN-END:variables
}
