import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sudeep99
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 340, 90);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Enter Password.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 240, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Enter Name.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 190, 120, 40);

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(260, 190, 200, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 390, 140, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 390, 140, 40);

        p1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(p1);
        p1.setBounds(260, 240, 200, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokedex/icons/Registration_Background.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-1270, -330, 2090, 970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int option = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit??");//Display message
    if(option == 0){
        Main_Page mainPage = new Main_Page();
        mainPage.setVisible(true);//Set the main page as visible
        dispose();//close current JFrame
    }            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String usr = t1.getText();// Fetch the username from textField t1
    String pwd = new String(p1.getPassword());//Fetch the password from JPasswordField
    try{
        Class.forName("java.sql.DriverManager");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/pokedex","root","psbb");
        /* Initialize connection with MYSQL access the database pokedex with  MYSQL username and password */
        Statement stmt = conn.createStatement();//Create a statement for exectution
        String query = "select * from users where name='"+usr +"' and password='"+pwd+"'";
        /* Query to get the users table from pokedex database where name is taken from TextField and password from PasswordField */
        ResultSet resultSet = stmt.executeQuery(query);
        /* Put the recieved contents after sucessfull execution of the statement String s in MYSQL in ResultSet "resultSet" */ 
        resultSet.first();
        if(resultSet.getRow() == 0){//If the result set is empty
            query = "insert into users values('"+usr+"','"+pwd+"')";//Insert the username and password in to the users table
            stmt.executeUpdate(query);//Execute the MYSQL update query 
            JOptionPane.showMessageDialog(this, "Registration Successful");// Show a message dialog
            progress progressFrame = new progress();
            progressFrame.setVisible(true);// set progress page as visible
            dispose();//close current JFrame
        }
        else{
            JOptionPane.showMessageDialog(this, "User name already exists.Try with another username");
            //If the result set is not empty, give a message that the username already exists
            t1.setText("");// clear the username field
            p1.setText("");//clear the password field
        }
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(this,ex.getMessage() );//Display error message
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
